name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - main
  pull_request: 
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Set up SSH
      uses: webfactory/ssh-agent@v0.5.3
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Configure AWS CLI
      run: |
        aws configure set aws_access_key_id ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws configure set aws_secret_access_key ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws configure set region ${{ secrets.AWS_DEFAULT_REGION }}

    - name: Upload DAG files to S3
      run: |
        aws s3 sync dags/ s3://team-okky-1-bucket/dags/ --delete
        aws s3 sync data/ s3://team-okky-1-bucket/data/ --delete
        aws s3 sync include/ s3://team-okky-1-bucket/include/ --delete

    - name: Deploy DAGs to EC2
      run: |
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-43-201-188-19.ap-northeast-2.compute.amazonaws.com 'aws s3 sync s3://team-okky-1-bucket/dags/ /home/ubuntu/airflow/dags --delete'
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-43-201-188-19.ap-northeast-2.compute.amazonaws.com 'aws s3 sync s3://team-okky-1-bucket/data/ /home/ubuntu/airflow/data'
        ssh -o StrictHostKeyChecking=no ubuntu@ec2-43-201-188-19.ap-northeast-2.compute.amazonaws.com 'aws s3 sync s3://team-okky-1-bucket/include/ /home/ubuntu/airflow/include'
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northeast-2'
