name: Deploy DAGs to Airflow

on:
  push:
    branches:
      - dev
  pull_request: 
    branches:
      - dev

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12.2'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: |
        pytest

    - name: Deploy to EC2
      env:
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: 'ap-northest-2'
      run: |
        scp -i team-okky-1-ec2-key.pem dags/*.py ec2-ubuntu@43.201.188.19:/home/ubuntu/airflow/dags
        ssh -i team-okky-1-ec2-key.pem ec2-ubuntu@43.201.188.19 'sudo systemctl restart airflow-scheduler'
